### ISSUE TITLE
substring expression < 0 issue when running for the first time.

### ISSUE THREAD

**Issue by SebastianKurp** [art-institute-of-chicago/aic-bash#6]
Hey super stoked I found this project!
I followed the instructions and it seems that I'm having errors running the script.
After git cloning the repo and running `./aic.sh` in the project directory I'm getting the following message in my console.
```
./aic.sh: line 371: -29: substring expression < 0
./aic.sh: line 372: -5: substring expression < 0
```
Any pointers or ideas on how to solve this would be awesome!

**Comment by IllyaMoskvin** [comment]
Thanks for the interest! Can you [check your bash version](https://www.cyberciti.biz/faq/how-do-i-check-my-bash-version/)? I suspect that your version is outdated. This script requires some features that are only present in bash v4.2 (Feb. 2011) or higher for performance reasons. From the readme:

> Likewise, macOS's default bash is locked to 3.2.57(1)-release due to licensing issues. Instructions for upgrading:
> 
> - [macos - Update bash to version 4.0 on OSX - Ask Different](https://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx)

We do have a branch where we started experimenting with making the script compatible with macOS's default bash, but it just ran terribly slow. You can take a look at it here:

https://github.com/art-institute-of-chicago/aic-bash/tree/bash-3.2.57

I'd recommend upgrading your bash via Homebrew instead of using that branch. The bash version that ships with macOS by default was released on November 7th, 2014! If there's more interest in keeping support for bash 3.2.57 despite the performance issues, we'll look into other solutions.

Hope this helps! Let us know if the issue proves to be something other than the bash version.

**Comment by SebastianKurp** [comment]
@IllyaMoskvin Perfect, thank you so much for the help!

**Comment by IllyaMoskvin** [comment]
@SebastianKurp Sure thing!
